### ISSUE TITLE
Inference using Audio or Text

### ISSUE THREAD

**Issue by ahmed-sharshar** [Advocate99/DiffGesture#12]
Hello, Dr. Zhu!
Thank you for your great work, it is really an outstanding work.
I Have run the model successfully, thanks to your great description. Now I want to use the model on arbitrary audio, how to do so? I tried editing on the dataloder but it seems mistiness for me.
Also I wonder if it is possible to run the model on a given text only, that to make it faster as the speed is a matter to me?
Thank you

**Comment by Advocate99** [comment]
Hi, thanks for your interest.
You can write a new script for testing the arbitrary audio. Maybe you can refer to the inferecence code and feed the model with the input of the same format. For the audio data processing, you may refer to the dataloader and other repos.
You may also need to use ffmpeg to copy with the raw audio.
There are some codes you may refer to. For example, you can write a script similar to this (https://github.com/yzhou359/MakeItTalk/blob/main/main_end2end.py). But it would be more difficult than what you want and I just mean you need a script like that.
For the input setting, my code only supports audio input and no test input is given. The modification is easy because you can refer to the code of Trimodal (https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context) where multiple inputs are used for training. You shall retrain the modal on the text input.

**Comment by ahmed-sharshar** [comment]
Thank you so much for your help, I will try that.
I was wondering how quickly you can expect to produce only the 3d poses spots without even making a video of them. In other words, If I have speech audio of 60 seconds, what is the expected time the model takes to just generate 3d poses for 60 seconds with frame rate = 15, because when I calculated the RTF, it is almost = 1.5 (takes on average 90 second to generate 60 seconds of poses without making a video), this value is relatively slow as speech2gesture model takes almost 0.1RTF.
Is the values I got are correct or I did something wrong?, If so, What is the RTF you got?
I really appreciate your help, Thanks a lot.

**Comment by Advocate99** [comment]
Sorry, I am not sure about the detailed speed. It may also relate with the environment.
Can you check the poses with visualization? If the results are normal, I think there is nothing wrong.
