### ISSUE TITLE
How can I get gesture from_text?

### ISSUE THREAD

**Issue by bonggyuKim** [Advocate99/DiffGesture#8]
Thanks for your work!! I watched HA2G, and there was a from_text mode.
How can I get gesture from_text mode?

**Comment by Advocate99** [comment]
Hi, yes, in this code we do not investigate the generation from text.
But in fact, the pipeline is similar. And there are some files should be modified if we want to support from_text mode: config files, pose_diffusion.py, the training and testing files involving the dataloader. They can be done following the code of Trimodal and HA2G. We only consider the audio driven setting for simplification (involving the multi-modal is not the core of illustrating the diffusion pipeline since we can just concat the features like Trimodal and can also only consider text-driven setting like some other papers.) Thanks.

**Comment by bonggyuKim** [comment]
Thank you for your answer!
